# Generated by Django 4.1 on 2022-09-13 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Produtos',
            fields=[
                ('id_produto', models.AutoField(db_column='ID_PRODUTO', primary_key=True, serialize=False)),
                ('nome_produto', models.TextField(blank=True, db_column='NOME_PRODUTO', null=True)),
                ('mercado', models.TextField(blank=True, db_column='MERCADO', null=True)),
                ('preco_produto', models.FloatField(blank=True, db_column='PRECO_PRODUTO', null=True)),
                ('imagem_produto', models.TextField(blank=True, db_column='IMAGEM_PRODUTO', null=True)),
                ('link_produto', models.TextField(blank=True, db_column='LINK_PRODUTO', null=True)),
                ('data_produto', models.TextField(blank=True, db_column='DATA_PRODUTO', null=True)),
            ],
            options={
                'db_table': 'produtos',
                'managed': False,
            },
        ),
    ]
