# Generated by Django 4.1 on 2022-10-05 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_produtos_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='produtos',
            options={'managed': False},
        ),
    ]
