# Generated by Django 4.1 on 2022-10-11 20:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_produtos_options'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='produtos',
            table='Produtos',
        ),
    ]
