class filtros:
    def __init__(self):
        self.key_words = ['TEMPERO','CALDINHO', 'CEREAL', 'CHA', 'SEMENTE', 'FILTRO', 'FORNO', 'ALUMINIO', 
    'SOJA', 'YAKISOBA', 'SALGADINHO', 'SNACK', 'PASSATA', 'ESMALTE', 'TOALHA', 'SARDINHA', 'ATUM', 'CANUDO', 'GUARDANAPO', 'BANHA', 'CONSERVA',
    'TABLETE', 'CONGELADO', 'COZIDO', 'KIT', 'INSTANTANEO', 'CREME', 'POTE', 'SHAMPOO', 'CONDICIONADOR', 'LATA', 'PAPINHA', 'PANELA', 'MINGAU', 'CHIPS', 'PRONTO',
    'INSTANTANEA', 'MANTEIGA','ESPUMANTE', 'RACAO', 'CHOCOLATE', 'CACAU', 'CARNE', 'SABOR', 'VINAGRE', 'BISCOITO', 'CAES', 'GATOS', 'BEBIDA', 'ENERGETICO', 'COLHER',
    'COADOR', 'BALA', 'CAFETEIRA', 'CAFEIRA', 'CHINELO', 'CAFUNE', 'GELEIA', 'PAO', 'TAPIOCA', 'GRANOLA', 'PRESUNTO', 'BOLO', 'TORRONE', 'CHIPS', 'PEGADOR', 'TORTA', 'CUSCUZ', 'MUFFINS',
    'TORRADA', 'BAGUETE', 'GARFO', 'AVEIA', 'BROA', 'CUP', 'LEITE', 'PANETTONE']